[package]
name = "blockchain-rs"
version = "0.1.0"
authors = ["Afnan Enayet <afnan.enayet@gmail.com>"]

[dependencies]
serde_json = "1.0"
pencil = "0.3.0"

[lib]
name = "rustchain"
path = "src/lib.rs"

[[bin]]
name = "rustchain-web"
path = "src/main.rs"

